const batchListData = [
  {
    id: 1,
    batchName: 'IAL Physics A2 - AZ Batch 1',
    batchDetails: 'Morning batch (Mon-Wed-Fri)',
    batchMsg: 'Batch starts next week',
    subjectName: 'IAL Physics A2 - AZ',
    regStartDate: '2023-07-01',
    regEndDate: '2023-09-01',
    status: 'Active',
  },
  {
    id: 2,
    batchName: 'IAL Physics AS - AZ Batch 2',
    batchDetails: 'Evening batch (Tue-Thu)',
    batchMsg: 'Seats limited',
    subjectName: 'IAL Physics AS - AZ',
    regStartDate: '2023-08-01',
    regEndDate: '2023-10-01',
    status: 'Active',
  },
  {
    id: 3,
    batchName: 'IGCSE Physics - AZ Batch A',
    batchDetails: 'Weekend batch',
    batchMsg: '',
    subjectName: 'IGCSE Physics - AZ',
    regStartDate: '2023-09-01',
    regEndDate: '2023-11-01',
    status: 'Active',
  },
  {
    id: 4,
    batchName: 'IGCSE Further Pure Math - ZIA',
    batchDetails: 'Intensive prep',
    batchMsg: 'Registration open',
    subjectName: 'IGCSE Further Pure Mathematics - ZIA',
    regStartDate: '2023-06-15',
    regEndDate: '2023-08-15',
    status: 'Active',
  },
  {
    id: 5,
    batchName: 'IGCSE Math B - ZIA Batch 1',
    batchDetails: '',
    batchMsg: '',
    subjectName: 'IGCSE Mathematics B - ZIA',
    regStartDate: '2023-05-01',
    regEndDate: '2023-07-01',
    status: 'Active',
  },
  {
    id: 6,
    batchName: 'Biology - IK Morning',
    batchDetails: 'Lab included',
    batchMsg: 'Limited slots',
    subjectName: 'Biology - IK',
    regStartDate: '2023-07-10',
    regEndDate: '2023-09-10',
    status: 'Active',
  },
  {
    id: 7,
    batchName: 'Human Biology - IK Evening',
    batchDetails: 'Evening batch',
    batchMsg: '',
    subjectName: 'Human Biology - IK',
    regStartDate: '2023-07-20',
    regEndDate: '2023-09-20',
    status: 'Active',
  },
  {
    id: 8,
    batchName: 'IGCSE English - AH',
    batchDetails: 'Grammar focus',
    batchMsg: '',
    subjectName: 'IGCSE English - AH',
    regStartDate: '2023-08-05',
    regEndDate: '2023-10-05',
    status: 'Active',
  },
  {
    id: 9,
    batchName: 'Bangla - MTE Batch',
    batchDetails: '',
    batchMsg: '',
    subjectName: 'Bangla - MTE',
    regStartDate: '2023-09-01',
    regEndDate: '2023-11-01',
    status: 'Active',
  },
  {
    id: 10,
    batchName: 'General Studies - Demo',
    batchDetails: 'Demo / trial',
    batchMsg: 'Free demo session',
    subjectName: 'General Studies',
    regStartDate: '2023-10-01',
    regEndDate: '2023-12-01',
    status: 'Active',
  },
];

export default batchListData;