const examListData = [
    {
        key: "1",
        examTitle: "VECTORS TEST 1",
        examType: "CLASS TEST",
        examDetails: "January 2022",
        subjectExam: "IAL Mathematics P3P4 - AJM",
        batchName: "IAL A2 OCT 25/ JAN 26",
        isActive: "Active",
    },
    {
        key: "2",
        examTitle: "Unit 4 premock",
        examType: "MOCK",
        examDetails: "January 2022",
        subjectExam: "IAL Chemistry A2",
        batchName: "IAL A2 CHEMISTRY OCT 2025 B#1",
        isActive: "Active",
    },
    {
        key: "3",
        examTitle: "Unit 4 mock 2",
        examType: "MOCK",
        examDetails: "July 2023",
        subjectExam: "IAL Chemistry A2",
        batchName: "IAL A2 CHEMISTRY OCT 2025 B#1",
        isActive: "Active",
    },
    {
        key: "4",
        examTitle: "Unit 4 Mock 1",
        examType: "MOCK",
        examDetails: "January 2022",
        subjectExam: "IAL Chemistry AS",
        batchName: "IAL A2 CHEMISTRY OCT 2025 B#1",
        isActive: "Active",
    },
    {
        key: "5",
        examTitle: "Unit 3 mock 2",
        examType: "MOCK",
        examDetails: "January 2022",
        subjectExam: "IAL Physics AS",
        batchName: "IAL– AS Physics Jan 2025 B#1",
        isActive: "Active",
    },
    {
        key: "6",
        examTitle: "Unit 2 premock",
        examType: "MOCK",
        examDetails: "July 2023",
        subjectExam: "IAL Physics AS",
        batchName: "IAL– AS Physics Jan 2025 B#1",
        isActive: "Active",
    },
    {
        key: "7",
        examTitle: "Unit 2 Mock 3",
        examType: "MOCK",
        examDetails: "July 2023",
        subjectExam: "IAL Physics AS",
        batchName: "IAL AS Chemistry Oct 2025 B#1",
        isActive: "Active",
    },
    {
        key: "8",
        examTitle: "Unit 3 mock 2",
        examType: "MOCK",
        examDetails: "January 2022",
        subjectExam: "IAL Physics AS",
        batchName: "IAL– AS Physics Jan 2025 B#1",
        isActive: "Active",
    },
    {
        key: "9",
        examTitle: "Unit 2 premock",
        examType: "MOCK",
        examDetails: "July 2023",
        subjectExam: "IAL Physics AS",
        batchName: "IAL– AS Physics Jan 2025 B#1",
        isActive: "Active",
    },
    {
        key: "10",
        examTitle: "Unit 2 Mock 3",
        examType: "MOCK",
        examDetails: "July 2023",
        subjectExam: "IAL Physics AS",
        batchName: "IAL AS Chemistry Oct 2025 B#1",
        isActive: "Active",
    },
];

const ExamType = [
    { label: "CLASS TEST", value: "CLASS TEST" },
    { label: "MOCK", value: "MOCK" },
    { label: "PREMOCK", value: "PREMOCK" },
] 

const marksheetData = [
    {
      key: "1",
      name: "Ariana Rahman",
      contact: "01712345678",
      fatherName: "Abdul Rahman",
      motherName: "Nasima Begum",
    },
    {
      key: "2",
      name: "Rafiul Hasan",
      contact: "01787654321",
      fatherName: "Kamrul Hasan",
      motherName: "Mitu Akter",
    },
    {
      key: "3",
      name: "Nusrat Jahan",
      contact: "01822334455",
      fatherName: "Rezaul Karim",
      motherName: "Laila Parvin",
    },
    {
      key: "4",
      name: "Tanim Ahmed",
      contact: "01699887766",
      fatherName: "Anis Ahmed",
      motherName: "Farzana Yasmin",
    },
    {
      key: "5",
      name: "Maliha Noor",
      contact: "01533445566",
      fatherName: "Nurul Alam",
      motherName: "Shirin Akhter",
    },
    {
      key: "6",
      name: "Arif Chowdhury",
      contact: "01766554433",
      fatherName: "Saidur Chowdhury",
      motherName: "Rubina Khatun",
    },
    {
      key: "7",
      name: "Zara Islam",
      contact: "01999887722",
      fatherName: "Imran Islam",
      motherName: "Sadia Sultana",
    },
    {
      key: "8",
      name: "Hasib Mahmud",
      contact: "01455667788",
      fatherName: "Mokbul Mahmud",
      motherName: "Sufia Begum",
    },
    {
      key: "9",
      name: "Raisa Akter",
      contact: "01744433322",
      fatherName: "Bashir Uddin",
      motherName: "Rokeya Akter",
    },
    {
      key: "10",
      name: "Tahmid Hasan",
      contact: "01811223344",
      fatherName: "Khaled Hasan",
      motherName: "Nargis Begum",
    },
  ];


export { examListData, ExamType , marksheetData };