const sectionListData = [
  {
    id: 1,
    sectionName: 'Batch 01',
    subjectName: 'IGCSE Further Pure Mathematics - AJM',
    batchName: 'IGCSE Pure Mathematics Nov 2025 (AJM) B#1',
    seatsEmpty: 36,
    seatsFilled: 16,
    totalSeats: 50,
    status: 'Active',
  },
  {
    id: 2,
    sectionName: 'Batch 01',
    subjectName: 'IGCSE Mathematics B - AJM',
    batchName: 'IGCSE Mathematics B (AJM) Nov 2025 B#1',
    seatsEmpty: 44,
    seatsFilled: 32,
    totalSeats: 60,
    status: 'Active',
  },
  {
    id: 3,
    sectionName: 'Batch 01',
    subjectName: 'IGCSE Further Pure Mathematics - AJM',
    batchName: 'IGCSE Mathematics B (AJM) Nov 2025 B#1',
    seatsEmpty: 21,
    seatsFilled: 18,
    totalSeats: 50,
    status: 'Active',
  },
  {
    id: 4,
    sectionName: 'Batch 01',
    subjectName: 'IGCSE English - MSM',
    batchName: 'IGCSE English Nov 2026 (MSM) B#1',
    seatsEmpty: 48,
    seatsFilled: 35,
    totalSeats: 60,
    status: 'Active',
  },
  {
    id: 5,
    sectionName: 'Batch 01',
    subjectName: 'Standard 8',
    batchName: 'Standard-8 Boys & Girls 2025-2026 AGCS',
    seatsEmpty: 12,
    seatsFilled: 16,
    totalSeats: 30,
    status: 'Active',
  },
  {
    id: 6,
    sectionName: 'Batch 01',
    subjectName: 'Standard 7',
    batchName: 'Standard-7 Boys & Girls 2025-2026 AGCS',
    seatsEmpty: 40,
    seatsFilled: 9,
    totalSeats: 50,
    status: 'Active',
  },
  {
    id: 7,
    sectionName: 'Batch 02',
    subjectName: 'IAL Physics A2',
    batchName: 'IAL A2 Physics May 2026 B#1',
    seatsEmpty: 37,
    seatsFilled: 16,
    totalSeats: 50,
    status: 'Active',
  },
  {
    id: 8,
    sectionName: 'Batch 02',
    subjectName: 'IGCSE Chemistry',
    batchName: 'IGCSE CHEMISTRY OCT 2025 B#1',
    seatsEmpty: 22,
    seatsFilled: 10,
    totalSeats: 50,
    status: 'Active',
  },
  {
    id: 9,
    sectionName: 'Batch 02',
    subjectName: 'IAL Mathematics P1,P2 - AJM',
    batchName: 'IAL AS Mathematics P1 & P2 May (AJM) 2026 B#2',
    seatsEmpty: 15,
    seatsFilled: 0,
    totalSeats: 50,
    status: 'Active',
  },
  {
    id: 10,
    sectionName: 'Batch 02',
    subjectName: 'IAL Biology AS',
    batchName: 'IAL AS Biology May 2026 B#1',
    seatsEmpty: 30,
    seatsFilled: 17,
    totalSeats: 50,
    status: 'Active',
  },
];

export default sectionListData;