const assignedStudentData = [
  {
    id: 1,
    studentName: 'Shafana mahmud',
    email: 'shafana@gmail.com',
    mobile: '8801575497968',
    passportNo: '200826920001378',
    batch: 'IAL - A2 Accounting May 2026 B#1',
    subject: 'IAL Accounting A2',
    section: 'Batch 01',
    specialFee: '----',
    deleteDate: '----',
    profileEdit: 'Profile Edit',
    downloadForm: 'Download form',
  },
  {
    id: 2,
    studentName: 'Adiyat Rahman',
    email: 'adiyat@gmail.com',
    mobile: '8801575497968',
    passportNo: '200826920001378',
    batch: 'IAL - A2 Accounting May 2026 B#1',
    subject: 'IAL Accounting A2',
    section: 'Batch 01',
    specialFee: '----',
    deleteDate: '----',
    profileEdit: 'Profile Edit',
    downloadForm: 'Download form',
  },
  {
    id: 3,
    studentName: 'Shafana mahmud',
    email: 'shafana@gmail.com',
    mobile: '8801575497968',
    passportNo: '200826920001378',
    batch: 'IAL - A2 Accounting May 2026 B#1',
    subject: 'IAL Accounting A2',
    section: 'Batch 01',
    specialFee: '----',
    deleteDate: '----',
    profileEdit: 'Profile Edit',
    downloadForm: 'Download form',
  },
  {
    id: 4,
    studentName: 'Shafana mahmud',
    email: 'shafana@gmail.com',
    mobile: '8801575497968',
    passportNo: '200826920001378',
    batch: 'IAL - A2 Accounting May 2026 B#1',
    subject: 'IAL Accounting A2',
    section: 'Batch 01',
    specialFee: '----',
    deleteDate: '----',
    profileEdit: 'Profile Edit',
    downloadForm: 'Download form',
  },
  {
    id: 5,
    studentName: 'Shafana mahmud',
    email: 'shafana@gmail.com',
    mobile: '8801575497968',
    passportNo: '200826920001378',
    batch: 'IAL - A2 Accounting May 2026 B#1',
    subject: 'IAL Accounting A2',
    section: 'Batch 01',
    specialFee: '----',
    deleteDate: '----',
    profileEdit: 'Profile Edit',
    downloadForm: 'Download form',
  },
  {
    id: 6,
    studentName: 'Shafana mahmud',
    email: 'shafana@gmail.com',
    mobile: '8801575497968',
    passportNo: '200826920001378',
    batch: 'IAL - A2 Accounting May 2026 B#1',
    subject: 'IAL Accounting A2',
    section: 'Batch 01',
    specialFee: '----',
    deleteDate: '----',
    profileEdit: 'Profile Edit',
    downloadForm: 'Download form',
  },
  {
    id: 7,
    studentName: 'Shafana mahmud',
    email: 'shafana@gmail.com',
    mobile: '8801575497968',
    passportNo: '200826920001378',
    batch: 'IAL - A2 Accounting May 2026 B#1',
    subject: 'IAL Accounting A2',
    section: 'Batch 01',
    specialFee: '----',
    deleteDate: '----',
    profileEdit: 'Profile Edit',
    downloadForm: 'Download form',
  },
  {
    id: 8,
    studentName: 'Shafana mahmud',
    email: 'shafana@gmail.com',
    mobile: '8801575497968',
    passportNo: '200826920001378',
    batch: 'IAL - A2 Accounting May 2026 B#1',
    subject: 'IAL Accounting A2',
    section: 'Batch 01',
    specialFee: '----',
    deleteDate: '----',
    profileEdit: 'Profile Edit',
    downloadForm: 'Download form',
  },
];

 const classRoutineData = [
  {
    id: 1,
    sat: '',
    sun: '02:00 to\n03:15 Pm',
    mon: '',
    tue: '02:00 to\n03:15 Pm',
    wed: 'AA',
    thu: 'AA',
    fri: '',
  },
  {
    id: 2,
    sat: '',
    sun: '02:00 to\n03:15 Pm',
    mon: '',
    tue: '',
    wed: '',
    thu: '',
    fri: '02:00 to\n03:15 Pm',
  }
];

export { assignedStudentData , classRoutineData };